### ISSUE TITLE
Are the reported sceptre p-values adjusted?

### ISSUE THREAD

**Issue by ejagoda14** [Katsevich-Lab/sceptre#100]
I understand from the documentation that the reported Significant column indicates whether the E-G link's p-value survived multiple hypothesis correction for the given alpha. I assume based on the values that I'm seeing the reported p-values are uncorrected, is there a way to derive the adjusted p-value from the sceptre object? Or should I just manually calculate these if needed?

Best,
Evvie

**Comment by timothy-barry** [comment]
Hi Evvie 🙂

> I understand from the documentation that the reported Significant column indicates whether the E-G link's p-value survived multiple hypothesis correction for the given alpha.

That's right.


>  I assume based on the values that I'm seeing the reported p-values are uncorrected

That's right, the p-values are uncorrected.

> is there a way to derive the adjusted p-value from the sceptre object? Or should I just manually calculate these if needed?

The adjusted p-values are not part of the sceptre_object. However, you can easily get the adjusted p-values (for the discovery analysis, for example) via the following code:

```
p.adjust(p = get_result(sceptre_object, "run_discovery_analysis")$p_value,
         method = sceptre_object@multiple_testing_method)
```

We likely will add the adjusted p-values as part of the standard output in a future update.

**Comment by timothy-barry** [comment]
Closing now.
