### ISSUE TITLE
How to take unperturbed cells as control?

### ISSUE THREAD

**Issue by Larrycpan** [Katsevich-Lab/sceptre#104]
I am dealing with high-MOI data, and the number of non-targeting cells is very small. I am wondering if sceptre can do DEG analysis between cells containing a given gRNA and all other gRNA negative cells (not containing any gRNAs). Thanks!

**Comment by timothy-barry** [comment]
Hello,

In high-MOI, very few (if any) cells contain exclusively non-targeting gRNAs. (It sounds like this is the case on your dataset.) Would the idea be to use cells containing zero gRNAs as the control group? (See [here](https://timothy-barry.github.io/sceptre-book/set-analysis-parameters.html) for a definition of control group.) Do you have a sense of how many cells contain zero gRNAs? Typically, only a handful of cells would contain zero gRNAs in a high-MOI screen.

**Comment by timothy-barry** [comment]
I see. This is not built into sceptre, but I think there probably is a hacky way to do this. Have you tried the standard approach yet?

**Comment by Larrycpan** [comment]
Ok, I'll try traditional single-cell DEG methods first. By the way, as to the STING-seq paper published in Science, I am confused how to determine the DEGs between gRNA+ cells and NT cells since the dataset is high-MOI. Are DEGs in Fig. 2C compared with 'complement set' or 'NT' cells? Since Fig. 2G shows the genes between sgRNA+ positive cells and NT. Thanks for you reply.

**Comment by timothy-barry** [comment]
>  I'll try traditional single-cell DEG methods first. 

I meant the standard sceptre approach of using the complement set as the control group (in high-MOI). But yes, bandwidth permitting, it would be good to evaluate traditional single-cell DEG methods as well. :)

> By the way, as to the STING-seq paper published in Science, I am confused how to determine the DEGs between gRNA+ cells and NT cells since the dataset is high-MOI. Are DEGs in Fig. 2C compared with 'complement set' or 'NT' cells? Since Fig. 2G shows the genes between sgRNA+ positive cells and NT. 

Yes, that figure is slightly confusing. Throughout the entire paper, the complement set was used as the control group. So "NT" does not literally mean NT.

**Comment by Larrycpan** [comment]
Thanks for your reply. I'll follow your suggestion.

**Comment by timothy-barry** [comment]
Great. You should feel free to let me know how that goes.

**Comment by timothy-barry** [comment]
Closing. Please feel free to open another issue if you'd like to continue this discussion.
