### ISSUE TITLE
Why aren't the processed assigned grna indexes in the raw assigned grna indexes?

### ISSUE THREAD

**Issue by jamesgalante** [Katsevich-Lab/sceptre#105]
Specifically, why doesn't the following line equate to TRUE for all indices in `sceptre_object@grna_assignments`:
`sceptre_object@grna_assignments$grna_group_idxs[[pert]] %in% sceptre_object@grna_assignments_raw$grna_group_idxs[[pert]]`

I'm trying to retrieve the cell indices for each guide for a given pert. In other words, for each pert, I can access the indices of all the cells for which a guide is considered present. But I want to access that information for each guide.

The following doesn't seem to line up if I have:
`get_grna_assignments <- function(sceptre_object) {
  if (!sceptre_object@functs_called[["assign_grnas"]]) {
    stop("`assign_grnas()` has not yet been called on the `sceptre_object`.")
  }
  return(sceptre_object@initial_grna_assignment_list)
}

individual_grna_assignments <- get_grna_assignments(sceptre_object)`

and 

`# Now add the individual "cre_perts"
get_cre_assignments <- function(sceptre_object) {
  if (!sceptre_object@functs_called[["assign_grnas"]]) {
    stop("`assign_grnas()` has not yet been called on the `sceptre_object`.")
  }
  return(sceptre_object@grna_assignments$grna_group_idxs)
}

individual_cre_assignments <- get_cre_assignments(sceptre_object)`. 

If I subset "individual_grna_assignments" for all the guides for a given `pert`, I would expect that all of the indices in "individual_cre_assignments[[pert]]" would exist in the union of the individual indices but that's not the case. This is the case for the "grna_assignments_raw" values of that pert.

**Comment by timothy-barry** [comment]
Hi James,

We have added a function to return the gRNA-to-cell assignments. This function will be part of version 0.9.3 of the software, which we will be releasing in a few weeks. I have copied and pasted the function (alongside its documentation) below. Please let me know if this helps resolve your issue.

```
#' Get gRNA assignments
#'
#' Obtains the gRNA-to-cell assignments from a `sceptre_object`. The output is a sparse logical matrix, with gRNAs in the rows and cells in the columns. A given entry of the matrix is TRUE if the given gRNA is assigned to the given cell.
#'
#' - When using the "maximum" assignment strategy, exactly one gRNA is assigned to a given cell. In other words, each column of the gRNA-to-cell assignment matrix contains exactly one TRUE entry.
#'
#' @param sceptre_object a `sceptre_object` that has had `assign_grnas()` called on it
#' @param apply_cellwise_qc a logical value (i.e., `TRUE` or `FALSE`) indicating whether to return the gRNA-to-cell assignment matrix after cellwise QC has been applied (default `FALSE`)
#'
#' @return a sparse logical matrix containing the gRNA-to-cell assignments
#' @export
#' @examples
#' library(sceptredata)
#' data(highmoi_example_data)
#' data(grna_target_data_frame_highmoi)
#' # import data
#' sceptre_object <- import_data(
#'   response_matrix = highmoi_example_data$response_matrix,
#'   grna_matrix = highmoi_example_data$grna_matrix,
#'   grna_target_data_frame = grna_target_data_frame_highmoi,
#'   moi = "high",
#'   extra_covariates = highmoi_example_data$extra_covariates,
#'   response_names = highmoi_example_data$gene_names
#' )
#' discovery_pairs <- construct_cis_pairs(sceptre_object)
#' sceptre_object <- sceptre_object |>
#'   set_analysis_parameters(
#'     discovery_pairs = discovery_pairs,
#'     side = "left"
#'   ) |>
#'   assign_grnas(
#'     method = "mixture", parallel = TRUE, n_processors = 2
#'   ) |>
#'   run_qc()
#'
#' grna_assignment_matrix <- get_grna_assignments(sceptre_object)
#' grna_assignment_matrix_with_qc <- get_grna_assignments(
#'   sceptre_object = sceptre_object,
#'   apply_cellwise_qc = TRUE
#' )
get_grna_assignments <- function(sceptre_object, apply_cellwise_qc = FALSE) {
  if (!sceptre_object@functs_called[["assign_grnas"]]) {
    stop("`assign_grnas()` has not yet been called on the `sceptre_object`.")
  }
  initial_grna_assignment_list <- sceptre_object@initial_grna_assignment_list
  grna_ids <- names(initial_grna_assignment_list)
  names(initial_grna_assignment_list) <- NULL
  j <- unlist(initial_grna_assignment_list)
  increment_vector(j, -1L)
  l <- vapply(initial_grna_assignment_list, length, FUN.VALUE = integer(1))
  p <- c(0L, cumsum(l))
  mat <- Matrix::sparseMatrix(j = 1, p = c(0, 1), repr = "R")
  mat@j <- j
  mat@p <- p
  mat@Dim <- c(
    length(initial_grna_assignment_list),
    get_grna_matrix(sceptre_object) |> ncol()
  )
  rownames(mat) <- grna_ids
  if (apply_cellwise_qc) {
    if (!sceptre_object@functs_called[["run_qc"]]) {
      stop("QC has not yet been called on this sceptre_object.")
    }
    mat <- mat[, sceptre_object@cells_in_use]
  }
  return(mat)
}
```

**Comment by timothy-barry** [comment]
Hey James,

We just updated the package. It is now easier to obtain the gRNA assignments. You may want to redownload the package and check [this](https://timothy-barry.github.io/sceptre-book/assign-grnas.html#returning-and-printing-the-grna-assignments) out.

Cheers,
Tim

**Comment by jamesgalante** [comment]
Hey Tim,

That’s a lot easier than what I was using - thank you!

Best,
James

**Comment by timothy-barry** [comment]
Great, closing.

Also, I'm not sure how big your screen is, but potentially you (or some of your labmates) would be interested in exploring the new [large-scale functionality](https://timothy-barry.github.io/sceptre-book/at-scale.html) :)
