### ISSUE TITLE
print(sceptre_object) not working in ver10 for object created in previous ver

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#107]
Hello!

I installed the latest version (10) and tried to import a sceptre object created in a previous version (9).
I found that the command `print(sceptre_object)` does not work and throw errors.
Just typing `sceptre_object` and running doesn't work either.
However, this command seems to work.
```
discovery_result <- get_result(
  sceptre_object = obj,
  analysis = "run_discovery_analysis"
)
```
Is it just the print command problem?
Should I re-run the analysis with version 10 for compatibility?

Thank you,

Jiseok

**Comment by timothy-barry** [comment]
Hi Jiseok,

Yes, you will need to recreate the `sceptre_object` and rerun the analysis to use version 0.10.0. However, you should be able to use the exact same code to do so.

**Comment by redbybeing** [comment]
Gotcha. Thank you!!
