### ISSUE TITLE
could not find function "compute_genes_within_distance"

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#108]
Hello,

When I try to run `construct_cis_pairs()`, I get this error message:
```
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `grna_target` doesn't exist.
```
I made sure the `grna_target` column exists in the `grna_target_data_frame`, so I don't think that's the problem.

I tried running the function `construct_cis_pairs()` line by line.
Then I got this error: 
```
Error in compute_genes_within_distance(midpoint, response_posits, distance_threshold) :
could not find function "compute_genes_within_distance"
```
So I think the above Error in `dplyr::select()` comes from the function `compute_genes_within_distance ` not existing.
Would that be the case? I am using the latest version 10.

Thank you so much!

Best,
Jiseok

**Comment by timothy-barry** [comment]
Hi Jiseok,

Strangely, someone else had this [issue as well](https://github.com/Katsevich-Lab/sceptre/issues/63), but for a previous version of the package. Unfortunately, that issue was not resolved.

Could you load the package as follows? git clone the `sceptre` repo (`git clone git@github.com:Katsevich-Lab/sceptre.git`), then open the package by double-clicking on `sceptre.Rproj`, and then enter `devtools::load_all()` in the console. When you do this, does the situation improve?

**Comment by timothy-barry** [comment]
Also, another thing to try would be to [uninstall and then reinstall the package](https://timothy-barry.github.io/sceptre-book/faq.html).

**Comment by timothy-barry** [comment]
Finally, could you enter `session_info()` and then paste the output? Thanks.

**Comment by ale-gomez** [comment]
Hey Tim,
  I can take it from here as I originally encountered this issue and asked Jiseok for help haha. I've gone ahead and tried the steps you specified above. Unfortunately, this does not improve or fix the issue. This happens after loading in a sceptre object with import_data() and proceeding to construct_cis_pairs() the error is as follows:
  Error in `dplyr::select()` at sceptre/R/pair_constructor_functs.R:49:2:
! Can't select columns that don't exist.
✖ Column `grna_target` doesn't exist.

**Comment by timothy-barry** [comment]
Got it, thanks Ale. Let us try to debug this. Thanks in advance for your patience; we might need to be persistent. :)

1. What happens when you enter `sceptre:::compute_genes_within_distance` in the console?

2. You have git cloned the `sceptre` repo, right? Could you open the file `sceptre/R/RcppExports.R`? Do you see the function `compute_genes_within_distance` defined within this file?

**Comment by ale-gomez** [comment]
No worries! Any help from you would be greatly appreciated so I'm happy to help with this.
1. When I do that, I get this:
```
function(midpoint, gene_tss_posits, distance_threshold) {
    .Call(`_sceptre_compute_genes_within_distance`, midpoint, gene_tss_posits, distance_threshold)
}
<environment: namespace:sceptre>
```
2. Yep! I cloned it into the same directory where I keep my other libraries and removed the previous sceptre directory prior to cloning into it. I opened `RcppExports.R` and I do see the function as:
```
compute_genes_within_distance <- function(midpoint, gene_tss_posits, distance_threshold) {
    .Call(`_sceptre_compute_genes_within_distance`, midpoint, gene_tss_posits, distance_threshold)
}
```

**Comment by timothy-barry** [comment]
Got it. What happens when you run the following in the console?

`sceptre:::compute_genes_within_distance(midpoint = 10,  gene_tss_posits = c(8,9,10,11,12), distance_threshold = 1)`

**Comment by ale-gomez** [comment]
Ok I get:
`[1] 2 3 4`

**Comment by timothy-barry** [comment]
Hm, OK. So the function does seem to be working, which is good.

What happens when you run the example within `construct_cis_pairs()`? That is:

```
library(sceptre)
library(sceptredata)
data(highmoi_example_data)
data(grna_target_data_frame_highmoi)
# import data
sceptre_object <- import_data(
  response_matrix = highmoi_example_data$response_matrix,
  grna_matrix = highmoi_example_data$grna_matrix,
  grna_target_data_frame = grna_target_data_frame_highmoi,
  moi = "high",
  extra_covariates = highmoi_example_data$extra_covariates,
  response_names = highmoi_example_data$gene_names
)
positive_control_pairs <- construct_positive_control_pairs(sceptre_object)
discovery_pairs <- construct_cis_pairs(sceptre_object,
  positive_control_pairs = positive_control_pairs,
  distance_threshold = 5e6
)
```
Does this work? You might want to close and then reopen R.

**Comment by timothy-barry** [comment]
OK. Note that the example uses `import_data()`, so `construct_cis_pairs()` (in principle) works when called downstream of `import_data()`.

Could you load the package via the `load_all()` strategy again? But this time, after importing your data, could you run through `construct_cis_pairs()` line-by-line?

```
  if (!all(colnames(response_position_data_frame) %in% c("response_id", "chr", "position"))) {
    stop("`response_position_data_frame` must contain columns 'response_id', 'chr', and 'position'.")
  }
  grna_target_data_frame <- sceptre_object@grna_target_data_frame
  grna_target_data_frame <- data.table::as.data.table(grna_target_data_frame)
  response_ids <- rownames(get_response_matrix(sceptre_object))
  distance_threshold <- as.integer(distance_threshold)
  grna_targets_to_exclude <- c("non-targeting", as.character(positive_control_pairs$grna_target))

  # 1. subset grna group data frame so as to exclude non-targeting gRNAs and gRNA groups in grna_targets_to_exclude
  grna_target_data_frame <- grna_target_data_frame |> dplyr::filter(!(grna_target %in% grna_targets_to_exclude))

  # 2. subset response_position_data_frame so that only genes within response matrix remain
  response_position_data_frame <- response_position_data_frame |> dplyr::filter(response_id %in% response_ids)

  # 3. loop over chromosomes in grna group df
  unique_chrs <- unique(grna_target_data_frame$chr)
  out_pairs <- lapply(X = unique_chrs, FUN = function(unique_chr) {
    response_position_data_frame_curr_chr <- response_position_data_frame[response_position_data_frame$chr == unique_chr, ]
    response_posits <- response_position_data_frame_curr_chr$position
    response_ids <- response_position_data_frame_curr_chr$response_id
    grna_target_data_frame_curr_chr <- grna_target_data_frame[grna_target_data_frame$chr == unique_chr, ]

    # 4. loop over unique grna groups in grna group df curr chr
    unique_grna_targets <- unique(grna_target_data_frame_curr_chr$grna_target)
    lapply(X = unique_grna_targets, FUN = function(unique_grna_target) {
      x <- grna_target_data_frame_curr_chr[grna_target_data_frame_curr_chr$grna_target == unique_grna_target, ]
      min_posit <- min(x$start)
      max_posit <- max(x$end)
      midpoint <- as.integer(floor((min_posit + max_posit) / 2))
      paired_responses <- response_ids[compute_genes_within_distance(midpoint, response_posits, distance_threshold)]
      if (length(paired_responses) >= 1L) {
        data.table::data.table(response_id = paired_responses, grna_target = unique_grna_target)
      } else {
        NULL
      }
    }) |> data.table::rbindlist()
  }) |>
    data.table::rbindlist() |>
    as.data.frame() |>
    dplyr::select(grna_target, response_id)
```

**Comment by ale-gomez** [comment]
Ok so it runs fine up to `unique_chrs <- unique(grna_target_data_frame$chr)`. After running the `out_pairs` part this is what I get:
```
out_pairs <- lapply(X = unique_chrs, FUN = function(unique_chr) {
+   response_position_data_frame_curr_chr <- response_position_data_frame[response_position_data_frame$chr == unique_chr, ]
+   response_posits <- response_position_data_frame_curr_chr$position
+   response_ids <- response_position_data_frame_curr_chr$response_id
+   grna_target_data_frame_curr_chr <- grna_target_data_frame[grna_target_data_frame$chr == unique_chr, ]
+ 
+   # 4. loop over unique grna groups in grna group df curr chr
+   unique_grna_targets <- unique(grna_target_data_frame_curr_chr$grna_target)
+   lapply(X = unique_grna_targets, FUN = function(unique_grna_target) {
+     x <- grna_target_data_frame_curr_chr[grna_target_data_frame_curr_chr$grna_target == unique_grna_target, ]
+     min_posit <- min(x$start)
+     max_posit <- max(x$end)
+     midpoint <- as.integer(floor((min_posit + max_posit) / 2))
+     paired_responses <- response_ids[compute_genes_within_distance(midpoint, response_posits, distance_threshold)]
+     if (length(paired_responses) >= 1L) {
+       data.table::data.table(response_id = paired_responses, grna_target = unique_grna_target)
+     } else {
+       NULL
+     }
+   }) |> data.table::rbindlist()
+ }) |>
+   data.table::rbindlist() |>
+   as.data.frame() |>
+   dplyr::select(grna_target, response_id)
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `grna_target` doesn't exist.
```

**Comment by timothy-barry** [comment]
Thanks, we've made good progress so far. I think it would be helpful for me to try to reproduce the error on my machine using your data.

 Would you mind sending me a list containing your data? The list should contain fields `response_matrix`, `grna_matrix`, `grna_target_data_frame`, `moi`, `extra_covariates`, and `response_names` (i.e., the arguments you pass to `import_data()`). If you'd be able to send me the data (tbarry@hsph.harvard.edu), then I could take a closer look at what's going wrong.

**Comment by ale-gomez** [comment]
Ok will do. Thank you Tim for the help!

**Comment by ale-gomez** [comment]
Tim, would a sceptre object of these data work?

**Comment by timothy-barry** [comment]
My sense is that something might be going wrong with the `import_data()` function, so ideally you'd send the list containing the fields `response_matrix`, `grna_matrix`, `grna_target_data_frame`, `moi`, `extra_covariates`, and `response_names`. I don't think this should be any more difficult than sending the `sceptre_object`?

**Comment by ale-gomez** [comment]
Oh no not at all. I'm compiling this info now!

**Comment by timothy-barry** [comment]
Hi Ale, I think I figured out the issue.  The response IDs (i.e., the rownames of `response_matrix`) must be a subset of the `response_id` column of `gene_position_data_frame_grch38` when calling `construct_cis_pairs()`. You can view the first few rows of `gene_position_data_frame_grch38` via `head(gene_position_data_frame_grch38)`. I pushed a small update to the main branch to check that this condition is satisfied.

As a side note, I noticed that your `batch` variable is stored as an integer vector. Categorical variables such as `batch` should instead be stored as a character vector or factor vector.

I hope this helps!

**Comment by ale-gomez** [comment]
Hi Tim, this worked well all the way to the end now. Thank you so much as always for your help!

**Comment by timothy-barry** [comment]
Great! Closing.
