### ISSUE TITLE
Option to add cells with 0 counts for the target in run_qc()

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#110]
Hi!

As far as I understand, in QC step, for a given gene-gRNA pair, sceptre removes cells (both ctrl & perturbed) where the target gene count is 0.
Our team found that for our dataset, there is a great need for including cells with 0 counts for the target gene in `run_qc()`.
Is there an easy way to do that?

Thank you so much!

Best,
Jiseok

**Comment by timothy-barry** [comment]
Hi Jiseok,

Would you mind adding this question to the [Discussion page](https://github.com/Katsevich-Lab/sceptre/discussions/categories/q-a)? We are trying to reserve issues for bugs.
