### ISSUE TITLE
Error in convert_covariate_df_to_design_matrix(covariate_data_frame = sceptre_object@covariate_data_frame,  :    The `formula_object` contains redundant information. This often occurs when one variable is `nested` inside another. For example, if the data frame contains a column `lane` with levels `lane_1`, `lane_2`, `lane_3`, and `lane_4` and a column `batch` with levels `batch_1` and `batch_2`, and if `lane_1` and `lane_2` are contained entirely within `batch_1` while `lane_3` and `lane_4` are contained entirely within `batch`2`, then `batch` is redundant. In this case `batch` should be removed from the formula object.

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#114]
Hi,

I am suddenly getting this error when I try to run `set_analysis_parameters()`

```
Error in convert_covariate_df_to_design_matrix(covariate_data_frame = sceptre_object@covariate_data_frame,  : 
  The `formula_object` contains redundant information. This often occurs when one variable is `nested` inside another. For example, if the data frame contains a column `lane` with levels `lane_1`, `lane_2`, `lane_3`, and `lane_4` and a column `batch` with levels `batch_1` and `batch_2`, and if `lane_1` and `lane_2` are contained entirely within `batch_1` while `lane_3` and `lane_4` are contained entirely within `batch`2`, then `batch` is redundant. In this case `batch` should be removed from the formula object.
```

The error message is quite self explanatory- but I'm puzzled because in my formula_object I don't think anything is nested.
My formula object is just this: `formula(~ log(response_n_umis) + log(response_n_nonzero) + log(grna_n_umis) + log(grna_n_nonzero) + batch_num + response_p_mito)`

And sceptre 10 has been running well without this error message just few days ago.

Thank you so much for helping out and I'm sorry to bother you so often!

Best,
Jiseok

**Comment by timothy-barry** [comment]
Hi Jiseok,

Thanks for bringing this to our attention. You'll notice that v.0.10.0 has not been updated for three weeks, so it's surprising that the code would be working a few days ago but not now.

Do you think you would be able to send me your `covariate_data_frame`? You can access this object via `sceptre_object@covariate_data_frame`. Also, my email is tbarry@hsph.harvard.edu. Thanks.

**Comment by redbybeing** [comment]
Hi Tim,

Yeah the sceptre version hasn't changed but the dataset I'm using slightly changed so perhaps that's causing some problem. I will email you soon.

Best,
Jiseok

**Comment by redbybeing** [comment]
Tim!

I found where the error comes from.
My `batch_num` column in covariate dataframe was a factor, and there were 10 batches but 12 levels. I think that caused trouble.
I converted `batch_num` column to character, got rid of those factor levels, and then it works well!

**Comment by timothy-barry** [comment]
Ah, strange. Thanks for catching this!

**Comment by timothy-barry** [comment]
Pushed a check for this situation on the dev branch.
