### ISSUE TITLE
Getting an errror when running the example code in "The Whole Game"

### ISSUE THREAD

**Issue by jamesgalante** [Katsevich-Lab/sceptre#119]
When I try to create a sceptre object with the example code in "The Whole Game"
```
# load the data, creating a sceptre_object
directories <- paste0(
  system.file("extdata", package = "sceptredata"),
  "/highmoi_example/gem_group_", 1
)
data(grna_target_data_frame_highmoi)
sceptre_object <- import_data_from_cellranger(
  directories = directories,
  moi = "high",
  grna_target_data_frame = grna_target_data_frame_highmoi
)
```
I get the following error:

```
Error in `$<-.data.frame`(`*tmp*`, feature_w_max_expression, value = character(0)) : 
  replacement has 0 rows, data has 21494
```

I looked into this a bit and it seems like it localizes to a C++ function:

```
.Call(`_sceptre_compute_cell_covariates_cpp`, i, p, x, n_genes, 
    n_cells, mt_gene_idxs, compute_p_mito, compute_max_feature)
```
    
Such that when called I get the error:

```
Error in .Call(`_sceptre_compute_cell_covariates_cpp`, i, p, x, n_genes,  : 
  Incorrect number of arguments (8), expecting 7 for '_sceptre_compute_cell_covariates_cpp'
```

I don't know if this is the actual problem, but this is all in the function `compute_cell_covariates`. Specifically when it's called here:

```
grna_covariate_df <- compute_cell_covariates(matrix_in = grna_matrix, 
    feature_names = character(0), compute_p_mito = TRUE, 
    compute_max_feature = TRUE)
```

If we look at the function:

```
function (matrix_in, feature_names, compute_p_mito, compute_max_feature) 
{
  matrix_in <- set_matrix_accessibility(matrix_in, make_row_accessible = FALSE)
  if (compute_p_mito) {
    mt_gene_idxs <- grep(pattern = "^MT-", x = feature_names, 
      ignore.case = TRUE)
    compute_p_mito <- length(mt_gene_idxs) >= 1
  }
  else {
    mt_gene_idxs <- integer()
  }
  out <- compute_cell_covariates_cpp(i = matrix_in@i, p = matrix_in@p, 
    x = matrix_in@x, n_genes = nrow(matrix_in), n_cells = ncol(matrix_in), 
    mt_gene_idxs = mt_gene_idxs, compute_p_mito = compute_p_mito, 
    compute_max_feature = compute_max_feature)
  ret <- data.frame(n_nonzero = out$n_nonzero, n_umis = out$n_umi)
  if (compute_p_mito) 
    ret$p_mito <- out$p_mito
  if (compute_max_feature) {
    ret$frac_umis_max_feature <- out$frac_umis_max_feature
    ret$feature_w_max_expression <- rownames(matrix_in)[out$max_feature + 
      1L]
  }
  return(ret)
}
```
It seems like `out` doesn't have the necessary `frac_umis_max_feature` or `max_feature` for the `if (compute_max_feature)` line:

```
Browse[7]> str(out)
List of 2
 $ n_nonzero: int [1:21494] 2 1 1 1 1 3 1 1 1 1 ...
 $ n_umi    : num [1:21494] 20 38 7 29 13 50 11 8 17 21 ...
```

Let me know if you need any more information. I'm using stanford's cluster sherlock if that helps.

**Comment by timothy-barry** [comment]
Hey James,

Thanks for the careful detective work. A couple initial questions.

1. Are you using the most up-to-date versions of `sceptre` and `sceptredata` on sherlock?
2. Is this code working locally (e.g., on a desktop/laptop)?

**Comment by jamesgalante** [comment]
Yes - I just downloaded the most up-to-date versions, and this is when I'm getting the error.

In fact, when I use a previous version (0.9.1), the script works fine.

However this is all done through OnDemand, which hosts RStudio on the cluster. I think it's just that some module necessary for C++ isn't getting sent to OnDemand and this is the problem. 

Running this code in an R session directly in terminal (on the cluster) seems to get past the initial problem I was having. 

It's interesting that this issue is isolated to the RStudio session but only for the newest version

**Comment by jamesgalante** [comment]
Ran into some errors on local with installing devtools, but I'm assuming that would work given the success on the cluster terminal. For sherlock, I had to port gcc (gcc/12.1.0) to the RStudio session and everything worked out.
