### ISSUE TITLE
Bug report from Veronica

### ISSUE THREAD

**Issue by timothy-barry** [Katsevich-Lab/sceptre#123]
Hi, 
I am currently using sceptre version 9.1 and while running the calibration I encountered an error (see below) and the calibration is not performed.

Running calibration_check in parallel. Change directories to /tmp/RtmpR92zW5/sceptre_logs/ and view the files calibration_check_*.out for progress updates.  ✓
Error in data.table::rbindlist(res, fill = TRUE) : 
  Item 1 of input is not a data.frame, data.table or list
In addition: Warning messages:
1: In parallel::mclapply(seq_along(partitioned_response_ids), function(proc_id) run_precomp_on_given_responses(partitioned_response_ids[[proc_id]],  :
  scheduled cores 1, 2, 3, 5, 6, 8, 10, 11, 14, 15, 19, 20, 23, 25, 26, 27, 28, 31, 32, 33, 36, 37, 40, 44, 45, 48 did not deliver results, all values of the jobs will be affected
2: In parallel::mclapply(seq_along(partitioned_grna_group_ids), function(proc_id) perform_association_analysis(partitioned_grna_group_ids[[proc_id]],  :
  all scheduled cores encountered errors in user code

_Originally posted by @VeronicaYumiceba in https://github.com/Katsevich-Lab/sceptre/discussions/122_

**Comment by timothy-barry** [comment]
Hi @VeronicaYumiceba,

It looks like the `sceptre_object` that you sent me was created using an older version of `sceptre`. Would you be able to download the latest version of `sceptre` and then recreate your `sceptre_object`? And then could you send me this updated `sceptre_object`? Alternately, could you send me a list containing the R objects that you used to construct the `sceptre_object` (i.e., `response_matrix`, `grna_matrix`, ..., `response_names`)? Thanks.

**Comment by VeronicaYumiceba** [comment]
I tried to assign more sources and different partitions for the task.

**Comment by timothy-barry** [comment]
Oh, so you are running the job in parallel on a cluster? My recommendation would be to (i) run the job locally on a laptop or (ii) use the sceptre Nextflow pipeline on the cluster. Sceptre does not work out-of-the-box in parallel mode on clusters.

On May 1, 2024, at 2:09 PM, VeronicaYumiceba ***@***.***> wrote:



I tried to assign more sources and different partitions for the task.

**Comment by timothy-barry** [comment]
I am happy to hear that it is working. However, `sceptre` is not designed to work out-of-the-box in parallel mode on clusters. My recommendation would be to (i) run the job locally on a laptop/desktop or (ii) use the sceptre Nextflow pipeline on the cluster.
