### ISSUE TITLE
The difference between sceptre or seurat Mixscape?

### ISSUE THREAD

**Issue by xiasijian** [Katsevich-Lab/sceptre#139]
I am sorry that I am a beginner for perturb-seq, I want to know how I can use the result of sceptre for the input of seurat?  Can the sceptre do clustering?

**Comment by xiasijian** [comment]
@ekatsevi

**Comment by timothy-barry** [comment]
Hi. No, `sceptre` and `Seurat` do not interoperate. `sceptre` does not currently do clustering. Its focus is on gRNA assignment and gRNA-to-gene association testing. The goal of `Seurat` mixscape is to remove ineffective perturbations (or cells that "escaped" perturbation). `sceptre` does not currently have functionality for removing ineffective perturbations, but we hope to add such functionality in the near future.

**Comment by xiasijian** [comment]
> Hi. No, `sceptre` and `Seurat` do not interoperate. `sceptre` does not currently do clustering. Its focus is on gRNA assignment and gRNA-to-gene association testing. The goal of `Seurat` mixscape is to remove ineffective perturbations (or cells that "escaped" perturbation). `sceptre` does not currently have functionality for removing ineffective perturbations, but we hope to add such functionality in the near future. In summary `sceptre` and `Seurat` can be thought of as complementary packages.

Thanks a lot. Your interpretation is so distinct.
