### ISSUE TITLE
Large-scale analysis available

### ISSUE THREAD

**Issue by Ruleof6** [Katsevich-Lab/sceptre#15]
Hi,

Is the large scale analysis available? We have an extensive dataset consisting of >500k cells and an MOI above 100. Seeing similar issues as described in your paper with inflated NTC p values using Monocles negative binomial model and your tool seems much more suitable.

Best,

James

**Comment by timothy-barry** [comment]
Hi James,

Thanks reaching out. The large-scale analysis pipeline is not quite available, but we should be able to set you up with a beta version. It would be best to discuss this over Zoom. Does this sound like a good plan to you? If so, could you please send me an email at tbarry2@andrew.cmu.edu?

**Comment by timothy-barry** [comment]
Just noting here that we are communicating instead over Zoom and email. Closing issue.
