### ISSUE TITLE
Run gRNA assignment error

### ISSUE THREAD

**Issue by nhu-github** [Katsevich-Lab/sceptre#157]
Hi,

I am trying to run [plot_response_grna_target_pair] but could not make it via Nextflow pipline.
So I got the sceptre_object and then try to re-run the assign_grnas and runqc to get a new sceptre_object that allow me to run function [plot_response_grna_target_pair].

Here when I run `assign_grnas` on the sceptre_object, I got error below:

sceptre_object <- assign_grnas(
  sceptre_object = sceptre_object,
  formula_object = formula_object,
  method = "mixture"
)

Error in set_matrix_accessibility(grna_matrix, make_row_accessible = TRUE) :
  Class not recognized.

**Comment by nhu-github** [comment]
close use_ondisc and got it work. looks like data formating issue

**Comment by timothy-barry** [comment]
Hi Nan, in your `assign_grnas()` function call, was `sceptre_object` derived from the Nextflow pipeline?
