### ISSUE TITLE
Parallel fail?

### ISSUE THREAD

**Issue by LPerlaza** [Katsevich-Lab/sceptre#21]
Hi,

I have been working with the last version of Sceptre and I am facing this error:
```
Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 23, 25, 26, 30 did not deliver results, all values of the jobs will be affected
```
when running: 
```
result<- run_sceptre_high_moi(gene_matrix = gene_matrix,
                               combined_perturbation_matrix = gRNA_test,
                               covariate_matrix = covariate_matrix,
                               gene_gRNA_group_pairs =group_pairs_test,
                               side = side,
                              parallel = TRUE,
                      storage_dir ="sceptre_outputs")
```

I tried debugging the function and realised that sometimes this error appears at the step of running ```run_gene_precomputation_at_scale_round_1``` and other times ```run_gene_precomputation_at_scale_round_2``` which suggests that the problem aren't the input objects but the parallezation. Therefore, I tried running the same command with ```parallel=FALSE```. This works fine (I have tested this in a small subset). However, it is not efficient for a whole data set. Do you have any ideas of how to solve this?

Thanks,
Laura

**Comment by timothy-barry** [comment]
Hi Laura,

Thanks for checking in. I do want to ask a few questions so that I can try to provide the best possible solution to this issue.

1. What sort of computer are you using? Laptop, desktop, cluster, etc.?
2. What operating system are you running? Linux vs windows, etc.?
3. How many cores do you have access to?

Thanks,
Tim

**Comment by LPerlaza** [comment]
Hi Tim,

Thanks for the reply.

1. I was working on a server
2. linux
3. 16 cores

**Comment by timothy-barry** [comment]
Got it, thanks. Unfortunately, I do not think that we will be able to debug the `mclapply` function. We simply are relying on this function to parallelize parts of the code; there is not much that we can do to fix it in specific cases in which it does not work.

There are two solutions. The first (and better) solution is to use the [sceptre Nextflow pipeline](https://github.com/timothy-barry/sceptre-pipeline) to carry out the analysis. We recently used this pipeline to analyze 200,000 gene-gRNA pairs from a large single-cell CRISPR screen dataset on a cluster; the pipeline finished in 3 hours, and each process used under 4GB of memory. Unfortunately the documentation for this pipeline is still a bit sparse, as the pipeline is new. Therefore, we'd probably want to schedule a Zoom meeting (for ~1 hour) to discuss this option.

The other (not as good) option is to use a single processor to analyze your whole dataset. What is your preference?

**Comment by LPerlaza** [comment]
oh Tim! Thanks! First solution sounds great. I will email you to your cmu email so we can arrange a zoom call. Thanks so much!

**Comment by timothy-barry** [comment]
Just noting here that we have migrated to email.
