### ISSUE TITLE
Running perturbation-to-gene association tests.rm: cannot remove '/work/appscr/r/jiseokl/Rtmpp2Fj14/logs': Directory not empty

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#25]
Hi,

I was trying to run high-MOI sceptre but it stopped with this error message. How can I fix this?

> Check /work/appscr/r/jiseokl/Rtmpp2Fj14/logs for more detailed status updates.
> Running checks and setting up directory structure.  ✓
> Running gene precomputations.  ✓
> Running perturbation precomputations.  ✓
> Running perturbation-to-gene association tests.rm: cannot remove '/work/appscr/r/jiseokl/Rtmpp2Fj14/logs': Directory not empty

I checked that error directory. There is nothing in the directory.

> (base) [jiseokl@longleaf-login5 logs]$ ls -la /work/appscr/r/jiseokl/Rtmpp2Fj14/logs
> total 0
> drwxr-xr-x 2 jiseokl users 4096 May 23 01:06 .
> drwx------ 2 jiseokl users 4096 May 23 01:06 ..

+Also, how long would it take for sceptre to run when the gene_gRNA_group_pairs has ~3 million pairs? How much memory should I request when I submit as a job in slurm?

**Comment by timothy-barry** [comment]
Note that the temporary directory changes each time you launch a new instance of R. I'd recommend determining the location of the working directory by calling `tempdir()` in R; next, `cd` to this directory and clear its contents.

**Comment by redbybeing** [comment]
I must have messed up something.. I restarted R session and re-ran sceptre. This time I reduced gene_gRNA_group_pairs to only 126 pairs (negative and positive controls only, no candidates). It goes all the way til here and then it just finishes and does not output 'result' anywhere. I don't see 'result' in my RStudio environment. 

> > result <- run_sceptre_highmoi(gene_matrix = gene_matrix,
> +                               combined_perturbation_matrix = perturbation_matrix,
> +                               covariate_matrix = covariate_matrix,
> +                               gene_gRNA_group_pairs = gene_gRNA_group_pairs,
> +                               side = side,
> +                               parallel = FALSE) # parallel = TRUE can cause issues in some machines
> Check /work/appscr/r/jiseokl/RtmpthBQpk/logs for more detailed status updates.
> Running checks and setting up directory structure.  ✓
> Running gene precomputations.  ✓
> Running perturbation precomputations.  ✓
> Running perturbation-to-gene association tests.>

**Comment by redbybeing** [comment]
I think it might have something do with tempdir(). After that error message, when I type tempdir(), nothing shows up. But before running the script, tempdir() shows a path.

**Comment by ekatsevi** [comment]
Do I understand correctly that you did not encounter this problem when you ran SCEPTRE yesterday on your positive control pairs?

**Comment by redbybeing** [comment]
Yes, when I ran yesterday with only positive controls, I got the result table dataframe.

**Comment by redbybeing** [comment]
I restarted R session then ran only the positive controls like yesterday, but same error occurred. Stopped here with no 'result' output. And tempdir() shows nothing.

Check /work/appscr/r/jiseokl/Rtmp7lGviw/logs for more detailed status updates.
Running checks and setting up directory structure.  ✓
Running gene precomputations.  ✓
Running perturbation precomputations.  ✓
Running perturbation-to-gene association tests.

**Comment by redbybeing** [comment]
I found this in `result_2.Rout` in `/work/appscr/r/jiseokl/Rtmp7lGviw/logs`
Perhaps relevant?

```
Running distilled CRT on gene Nfatc3 and gRNA guide-Nfatc3-2.
Error in .highmoi_run_gRNA_gene_pair_analysis_at_scale(pod_id = pod_id,  : 
  task 1 failed - "argument is of length zero"
In addition: Warning messages:
1: In run_sceptre_highmoi(gene_matrix = gene_matrix, combined_perturbation_matrix = perturbation_matrix,  :
  Removing the following genes with low expressions (UMI count <250): guide-Anp32e-2 guide-Asphd1-2 guide-Eif1ad-2 guide-Kat5-1 guide-Maz-2 guide-Rbm26-2 guide-Rnaseh2c-2 guide-Smyd4-1
2: In run_sceptre_highmoi(gene_matrix = gene_matrix, combined_perturbation_matrix = perturbation_matrix,  :
  Removing the following perturbations with low counts (counts <30): guide-Anp32e-2 guide-Asphd1-2 guide-Eif1ad-2 guide-Kat5-1 guide-Maz-2 guide-Rbm26-2 guide-Rnaseh2c-2 guide-Smyd4-1. Consider grouping together perturbations that target the same site to circumvent this problem.
Error: object 'result' not found
[1] "/work/appscr/r/jiseokl/Rtmp7lGviw"
```

**Comment by redbybeing** [comment]
Ohhh I think I found out where it went wrong.
This time I set 
side <- "Both"
But yesterday I set side <- "left"
I changed back to side <- "left" and now I can see the result table..
Sorry.. is "both" case-sensitive? Should I input "Both" or "both" if I wanna test negative/positive/candidate altogether?

**Comment by ekatsevi** [comment]
> is "both" case-sensitive?

Yes.

> Should I input "Both" or "both" if I wanna test negative/positive/candidate altogether?

Please use "both" rather than "Both". Let me know if changing "Both" to "both" resolves your issue.

**Comment by redbybeing** [comment]
Yes, it works now when I use 'both'. I looked at the direction table in the tutorial and simply thought it was okay to use uppercase. I'm sorry for all the hassle. Thank you so much!

**Comment by timothy-barry** [comment]
Thanks. We'll add more correctness checks for the inputs.
