### ISSUE TITLE
Error when running calibration check on low MOI data

### ISSUE THREAD

**Issue by ale-gomez** [Katsevich-Lab/sceptre#26]
Hello! I am running into an error when running a calibration check in the low MOI. It looks like this: 

```r
Running setup.  ✓
Constructing negative control pairs. ✓
Generating permutation resamples. ✓
Running differential expression analyses.
Error in data.table::setorderv(ret, cols = c("p_value", "response_id"),  : 
  some columns are not in the data.table: p_value,response_id
In addition: Warning message:
In construct_negative_control_pairs(n_calibration_pairs, calibration_group_size,  :
  Unable to generate 31713 negative control pairs. Consider increasing `calibration_group_size`.
``` 
Below is what I'm running:
```r
calibration_result <- run_sceptre_lowmoi(
  response_matrix = response_matrix_lowmoi,
  grna_matrix = grna_matrix_lowmoi,
  covariate_data_frame = covariate_data_frame_lowmoi,
  grna_group_data_frame = grna_group_data_frame_lowmoi,
  formula_object = formula_object,
  response_grna_group_pairs = response_grna_group_pairs,
  calibration_check = TRUE # calibration_check TRUE
) 
``` 
One important note is that I only have one guide for my non-targeting group. Would that be the source of the issue? Is it not possible to run the calibration check unless there are multiple non-targeting guides in the non-targeting group?

**Comment by ekatsevi** [comment]
Indeed, unfortunately the calibration check works only if you have more than one non-targeting guide. We recommend having multiple non-targeting guides in your pooled CRISPR screen experiments. You can still apply `sceptre` to the targeting gRNAs, albeit without the peace-of-mind that the method is well-calibrated on your particular data.

**Comment by ale-gomez** [comment]
I see. I suspected that was the case. In that case, I continued to run the discovery analysis code:
```r
discovery_result <- [run_sceptre_lowmoi](https://katsevich-lab.github.io/sceptre/reference/run_sceptre_lowmoi.html)(
  response_matrix = response_matrix_lowmoi,
  grna_matrix = grna_matrix_lowmoi,
  covariate_data_frame = covariate_data_frame_lowmoi,
  grna_group_data_frame = grna_group_data_frame_lowmoi,
  formula_object = formula_object,
  response_grna_group_pairs = response_grna_group_pairs,
  calibration_check = FALSE # calibration check FALSE
)
``` 
But I still get another error here at this point in the analysis (it starts, but crashes at 1580/36601):
```r
Analyzing pairs containing response AC008937.3 (1580 of 36601)
Error: Error in function boost::math::skew_normal_distribution<double>::skew_normal_distribution: Shape parameter is nan, but must be finite!
``` 
Is this related to the above or something different?
Also, what is the reasoning behind having multiple non-targeting guides? Is it a way for the algorithm to have more confidence in the controls?

**Comment by ekatsevi** [comment]
> But I still get another error here at this point in the analysis (it starts, but crashes at 1580/36601)...Is this related to the above or something different?

We will get back to you on this shortly.

> Also, what is the reasoning behind having multiple non-targeting guides? Is it a way for the algorithm to have more confidence in the controls?

The calibration check proceeds by applying the test to each NT gRNA and each gene, making sure there the resulting p-values are not too small. The test consists of comparing the expression of the gene in cells containing the tested gRNA and cells containing _other_ NT gRNAs (please read our [preprint](https://doi.org/10.1101/2023.05.15.540875) for more details on the calibration check). If there is only one NT gRNA, then there are no cells left containing other NT gRNAs.

**Comment by timothy-barry** [comment]
Hello,

I'd like to try to help debug the error that you're encountering. As a starting point, could you call the `traceback()` function in the console and print the output so that we can get a better sense of which function might be causing issues? At some point it may be necessary for you to share a subset of your data.

Thanks.

**Comment by timothy-barry** [comment]
Hi Ale,

Thank you. This is a helpful starting point.

Would you be able to send (e.g., via email) the objects that you passed to the `run_sceptre_lowmoi` function? My email is tbarry2@andrew.cmu.edu.

**Comment by timothy-barry** [comment]
Hi Ale,

Thanks for the email. Could you please instead send your objects in `.rds` format? For example, you could execute the following code:

```
my_objects <- list(response_matrix = response_matrix_lowmoi,
  grna_matrix = grna_matrix_lowmoi,
  covariate_data_frame = covariate_data_frame_lowmoi,
  grna_group_data_frame = grna_group_data_frame_lowmoi,
  formula_object = formula_object,
  response_grna_group_pairs = response_grna_group_pairs)
saveRDS(my_objects, "~/my_objects.rds")
```

Then you could email `my_objects.rds`. Thanks!

**Comment by ale-gomez** [comment]
Hi Tim,
  Sent! I hope that helps.

**Comment by timothy-barry** [comment]
Great, thanks. I'll take a look and get back to you shortly.

**Comment by timothy-barry** [comment]
Hi Ale,

Thanks for sending the data. I believe that I located and fixed the bug. I am now able to run the method on your data without errors. Would you mind giving it a shot?

**Comment by ale-gomez** [comment]
Hi Tim,
  It's weird but I'm still getting the same error at the same point. I tried reinstalling the package but it didn't change. Maybe I'm missing something?
