### ISSUE TITLE
Export the number of cells for each gene-guide pair

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#27]
Hi,

Is there an easy way to export the number of cells for each guide-gene pair from the sceptre pipeline?
I want to check how cell # affects the DEG results.

Thanks,
Jiseok

**Comment by timothy-barry** [comment]
Hi Jiseok,

Unfortunately, the high MOI function does not currently return the number of cells for each pair. We'll be adding this functionality to our next update of the package.
