### ISSUE TITLE
High MOI when there's multiple guides targeting one gene

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#32]
Hi,

Suppose I have two guides targeting the same gene (guide1, guide2).
When running high-moi sceptre, my understanding is that it divides the cells into guide1+ vs guide1- for comparison.
In this case, guide1- group may include cells expressing guide2, which could dilute the differential expression effect. 
Is there an option to handle such case in high-moi sceptre? 
In other words, group cells into: guide1+ vs. (guide1- & guide2-)

I could combine guide1 and guide2 counts for each cell in advance to avoid this issue, but then I might not want to combine guides that turns out be ineffective thus diluting the signal. 

Best,
Jiseok

**Comment by ekatsevi** [comment]
Hi Jiseok,

The short answer to your question is that SCEPTRE does not currently have functionality to compare guide1+ vs. (guide1- & guide2-). This is an intriguing possibility, which we may consider implementing in the future. In the meantime, however, I hope to convince you that comparing guide1+ versus guide1- is not too bad either. Indeed,  in a high-MOI screen, gRNAs infect cells roughly independently of one another. Therefore, you would expect guide2 to be present in roughly the same proportion of guide1+ and guide1- cells. In this sense, the effect of guide2 will roughly "average out" when testing guide1. (This heuristic reasoning assumes that the effects of guides targeting the same gene are additive, which may or may not be the case in practice.)

Best,
Gene
