### ISSUE TITLE
High MOI combine_perturbations function error

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#33]
Hi,

I got this error when trying to run:
combined_perturbation_matrix <- combine_perturbations(perturbation_matrix = perturbation_matrix,
                                                      gRNA_groups_table = gRNA_groups_table)

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': 'x' must be an array of at least two dimensions

My gRNA_groups_table looks like this. It only has one guide (guide-GFP-1) for non-targeting group (guide-GFP). Is this causing a problem?

<img width="368" alt="Screenshot 2023-06-05 at 3 08 28 PM" src="https://github.com/Katsevich-Lab/sceptre/assets/61475990/9397b6cb-63e3-4f29-8a00-2e876e682798">

**Comment by timothy-barry** [comment]
Hi,

Thank you for pointing this out. I believe I fixed this bug. Could you please install the package and try again?

**Comment by redbybeing** [comment]
Hi Tim,

I reinstalled the package and now it runs without error. Thanks!

Best,
Jiseok
