### ISSUE TITLE
gRNA-to cell in SCEPTRE lowMOI

### ISSUE THREAD

**Issue by glettre** [Katsevich-Lab/sceptre#35]

**Comment by glettre** [comment]
Thanks for developing the SCEPTRE low-MOI tool. It is great.

Even in a low-MOI setting, it happens that the same cell can receive >1 gRNA. When that is the case, how does SCEPTRE lowMOI assigns gRNA-to-cell? From some analyses that we did, it does not look like it is only the top gRNA, but we could not find the threshold that is being used (even after reading the preprint). Thanks!

**Comment by ekatsevi** [comment]
> Thanks for developing the SCEPTRE low-MOI tool. It is great.

You are welcome! I am very glad you like the tool.

> Even in a low-MOI setting, it happens that the same cell can receive >1 gRNA. When that is the case, how does SCEPTRE lowMOI assigns gRNA-to-cell? From some analyses that we did, it does not look like it is only the top gRNA, but we could not find the threshold that is being used (even after reading the preprint). Thanks!

Thanks for bringing up this important point, which indeed is missing from our documentation. The approach SCEPTRE currently takes in the low-MOI regime is to assign to each cell the gRNA with highest UMI count. Other gRNAs with nonzero UMI counts often represent background noise during the sequencing and alignment steps. There may be some cells that actually have more than one gRNA, but SCEPTRE currently does not take this into account, assigning to each cell exactly one gRNA. Please note that if you would like to apply a more sophisticated gRNA-to-cell assignment, you can do so, and pass a logical `grna_matrix` to SCEPTRE (see [documentation](https://katsevich-lab.github.io/sceptre/reference/run_sceptre_lowmoi.html#note)). However, we still ask that the `grna_matrix` you pass to us has only one gRNA assigned to each cell.

**Comment by ekatsevi** [comment]
I've now updated the low-MOI vignette and function reference to clarify this point.
