### ISSUE TITLE
Definition of control cells

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#38]
Hello,

I understand that if I set the perturbation threshold to 3, cells that express minimum 3 UMI reads of the gRNA-of-interest is defined as 'perturbed'.

Then for the control cells, are they cells with zero gRNA-of-interest expression? Or cells with less than 3 reads of the gRNA are also included?

**Comment by ekatsevi** [comment]
Cells with fewer than 3 reads of the gRNA are also included as control cells.

**Comment by redbybeing** [comment]
Thanks Eugene!

**Comment by timothy-barry** [comment]
Marking as closed.
