### ISSUE TITLE
Covariates to include in new high-moi

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#39]
Hello,

New high-moi tutorial indicates that I first go through the low-moi tutorial since they're almost identical.

In low-moi tutorial, you recommended including `response_n_umis`, `response_n_nonzero`, and `p_mito` as covariates.
In the previous version of high-moi tutorial, you recommended including `lg_gene_lib_size`, `lg_gRNA_lib_size`, `batch`, and `p_mito`.

For the new high-moi, which covariates should I include?

Best,
Jiseok

**Comment by redbybeing** [comment]
Oh, also, do I have to stick to the covariate names as indicated in the tutorial, or can I substitute the name?
For example: `response_n_umis` <-> `nCount_RNA`, `bio_rep `<-> `batch`

**Comment by timothy-barry** [comment]
Ah, that is a good question. As a starting point, we'd recommend using `response_n_umis`, `response_n_nonzero`, `grna_n_umis`, `grna_n_nonzero`, `p_mito` and batch/biological replicate as covariates in high MOI. The log transformation of `response_n_umis`, `response_n_nonzero`, `grna_n_umis`,  and`grna_n_nonzero` should be specified within the formula object. It would be best to try to follow the experimental high MOI example as closely as possible.

**Comment by timothy-barry** [comment]
You can use whatever names you want for the covariates, provided that the column names of the covariate data frame are variables within the formula object.

**Comment by redbybeing** [comment]
Thank you!

**Comment by timothy-barry** [comment]
Happy to help, closing.
