### ISSUE TITLE
could not find function "run_sceptre_highmoi_experimental"

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#40]
Hi,

This could be a silly question, but after reinstalling sceptre with

```
devtools::install_github("katsevich-lab/sceptre")
library(sceptre)
```

I get this error message:

` could not find function "run_sceptre_highmoi_experimental"
`
I am trying to run the new highmoi sceptre. Is there anything I'm missing to get the updated version?

**Comment by timothy-barry** [comment]
Hm. I'd recommend deleting your currently installed version of `sceptre` and then reinstalling. To do so, open R and then issue the command `.libPaths()`. Your output should look something like this: `/Library/Frameworks/R.framework/Versions/4.2/Resources/library`. Next, within terminal, `cd` to the above directory (i.e., `cd /Library/Frameworks/R.framework/Versions/4.2/Resources/library`), and then delete `sceptre` via `rm -rf sceptre`. After this, try downloading the package again.

**Comment by redbybeing** [comment]
Thank you! The function is available after erasing and re-installing sceptre as you mentioned!

**Comment by timothy-barry** [comment]
Great, closing.
