### ISSUE TITLE
Two or more non-targeting gRNAs must be present when running a calibration check.

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#41]
Hello, 

I have another question..

I get this message when I try to run calibration check with `run_sceptre_highmoi_experimental`
```
Error in check_inputs(response_matrix, grna_matrix, covariate_data_frame,  : 
  Two or more non-targeting gRNAs must be present when running a calibration check. gRNAs that are non-targeting should be assigned a gRNA group label of 'non-targeting'.
```

Unfortunately, in my library, I only have one single gRNA (guide-GFP) as a non-targeting gRNA. All others are gene targeting gRNAs. I didn't know that it's better to include multiple non-targeting gRNAs when I first generated the library. In this case, what is the best action I can take to run sceptre new high-moi with my current data? Skip calibration and run discovery? 

I recall that in previous high-moi scepter, it didn't matter if I only had one single non-targeting gRNA, because I was able to define my own negative control pairs with just one non-targeting gRNA (GFPguide vs all genes).

**Comment by ekatsevi** [comment]
Hi Jiseok, I think this may be a bug; you should still be able to carry out a calibration check in high-MOI with just one gRNA. I'll let @timothy-barry address this further.

**Comment by timothy-barry** [comment]
The package no longer throws this error.
