### ISSUE TITLE
Error in set(x, j = name, value = value) :    Supplied 2 items to be assigned to 1355970 items of column 'formula'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code. Calls: $<- -> $<-.data.table -> set

### ISSUE THREAD

**Issue by redbybeing** [Katsevich-Lab/sceptre#42]
Hi!

I got this error while running new high-moi sceptre. I don't know what this means. Could you please help me?

Thank you!

```
Running precomputation on response Gm10931 (32260 of 32285)
Running precomputation on response AC149090.1 (32285 of 32285)
Analyzing pairs containing gRNA group Fxr1 (1 of 42)
Analyzing pairs containing gRNA group Asphd1 (5 of 42)
Analyzing pairs containing gRNA group Eif1ad (10 of 42)
Analyzing pairs containing gRNA group Hist2h3b (15 of 42)
Analyzing pairs containing gRNA group Mus81 (20 of 42)
Analyzing pairs containing gRNA group Paip2 (25 of 42)
Analyzing pairs containing gRNA group Rnaseh2c (30 of 42)
Analyzing pairs containing gRNA group Sfmbt1 (35 of 42)
Analyzing pairs containing gRNA group Zbtb18 (40 of 42)
Error in set(x, j = name, value = value) : 
  Supplied 2 items to be assigned to 1355970 items of column 'formula'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
Calls: $<- -> $<-.data.table -> set
Execution halted
```

**Comment by timothy-barry** [comment]
Hm. I do not think I have seen this error before. Might it be possible for you to produce a minimal reproducible example? Or might you be able to share a subset of your data that causes this error to occur?

As a backup option, you might consider using the permutation testing functionality. What happens when you run the above, setting `resampling_mechanism` to `permutations`?

**Comment by redbybeing** [comment]
I will first try resampling_mechanism = "permutations" and let you know how it goes. If I need to provide you my data for debugging, what is the best format? I'm not sure how to subset the data though in order to reproduce the error.

**Comment by timothy-barry** [comment]
As a starting point, which response-gRNA group pairs are you testing? The entire set of possible pairs? Or some subset?

**Comment by redbybeing** [comment]
I was running the entire set of possible pairs. 32285 genes x 42 gRNA groups = 1355970 pairs.

**Comment by redbybeing** [comment]
Hi Tim, I got a similar error after running with resampling_mechanism = "permutations"
```
Analyzing pairs containing response AC124606.2 (32280 of 32285)
Analyzing pairs containing response AC149090.1 (32285 of 32285)
Error in set(x, j = name, value = value) : 
  Supplied 2 items to be assigned to 1355970 items of column 'formula'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
Calls: $<- -> $<-.data.table -> set
Execution halted
```

**Comment by timothy-barry** [comment]
Hi Jiseok, my plan to to help you provide us with a minimal reproducible example so that we can get this resolved as quickly as possible.

As a starting point, could you please try to run the function on a smaller subset of pairs? For example, the following code selects 10 random pairs to analyze.

```
set.seed(4)
 response_grna_group_pairs <- response_grna_group_pairs |> dplyr::sample_n(10)
```

Could you please run this line of code before calling the function? Do you still see the error?

**Comment by redbybeing** [comment]
Hi Tim,

No hurries! I will then try running 10 random pairs until I run into a problematic subset, then send the subset information to you.

**Comment by redbybeing** [comment]
Hi Tim,

Looks like running these two lines always give the same 10 pairs.
```
set.seed(4)
response_grna_group_pairs <- response_grna_group_pairs |> dplyr::sample_n(10)
```
Anyways, running these 10 pairs didn't evoke an error and output this table with some NAs.
<img width="984" alt="Screenshot 2023-07-19 at 1 45 29 PM" src="https://github.com/Katsevich-Lab/sceptre/assets/61475990/26ac3ca2-dd51-4312-ba2d-27c379148bb8">

**Comment by timothy-barry** [comment]
I see. Would it be possible for you to send the data that you are passing to sceptre to my email (tbarry2@andrew.cmu.edu)? For example, could you run the following code and then email me `my_objects.rds`? This will help me debug more efficiently.

```
my_objects <- list(response_matrix = response_matrix,
                               grna_matrix = grna_matrix,
                               covariate_data_frame = covariate_data_frame,
                               grna_group_data_frame = grna_group_data_frame,
                               formula_object = formula_object,
                               calibration_check = calibration_check,
                               response_grna_group_pairs = response_grna_group_pairs)
saveRDS(my_objects, "~/my_objects.rds")
```

By the way, what value are you passing to the argument `output_amount`?

**Comment by redbybeing** [comment]
I sent you an email with required info! Thanks.

**Comment by timothy-barry** [comment]
The conversation continued over email. Closing.
