### ISSUE TITLE
Try to find bugs/errors using the low- and high-MOI example data.

### ISSUE THREAD

**Issue by jdeu1023** [Katsevich-Lab/sceptre#53]
E.g., running functions in a different sequence, altering the inputs

**Comment by timothy-barry** [comment]
We should pay particular attention to input checking:

"The data we are asking users to supply is somewhat complicated, and there are many ways to mess up. Ideally, Joseph would try every possible combination of malformed input and update the input checking code where necessary to make sure we have all our bases covered. There may also be situations where we need to choose between throwing an error and a warning. For example, if users specify a gRNA in the gRNA group data frame that is not present in the data, we could throw a warning and simply ignore that gRNA or we could throw an error."

**Comment by timothy-barry** [comment]
I carried out this sort of analysis last week; closing.
