### ISSUE TITLE
CRISPRi design considerations for using SCEPTRE-LR low moi

### ISSUE THREAD

**Issue by pipes82** [Katsevich-Lab/sceptre#59]
Thank you for your work on this tool. I am trying to decide on the best analysis tools for a CRISPRi Perturb-seq dataset that I will be analyzing. I had questions regarding whether signature generation was feasible given the experimental limitations. The data was generated with ~600 cells per perturbation, which I anticipate to yield ~300 cells per perturbation after sequencing. There should be ~ 2-2.5% negative controls (non-targeting and safe targeting) and ~3500 targeted genes at low moi.

Would this experimental set-up be appropriate for using SCEPTRE-LR (low moi) to determine the differential expression between targeted vs. NT?  I was curious what the minimum suggested cells per perturbation would be to generate biologically relevant signatures using the low MOI method? Also, do you have an optimum suggested number/percentage of negative controls? Any experimental design suggestions to optimize the use of SCEPTRE low moi?

Thank you for your help,
Mary

**Comment by ekatsevi** [comment]
>  I had questions regarding whether signature generation was feasible given the experimental limitations.

Could you clarify what you mean by "signature generation"? Are you referring to testing perturbation-gene pairs? 

> Would this experimental set-up be appropriate for using SCEPTRE-LR (low moi) to determine the differential expression between targeted vs. NT?

Yes, having around 300 cells per perturbation and about 3500*0.02 = 70 negative control perturbations sounds like a decent experimental design that I would expect to yield pretty good results. 

> I was curious what the minimum suggested cells per perturbation would be to generate biologically relevant signatures using the low MOI method? 

I'm not sure what you mean by "signatures" here, but perhaps you are wondering how many cells per perturbation you need in order for SCEPTRE to have power to detect an association with a gene of interest. This depends not just on the cells per perturbation but also the effect size of the perturbation on the gene and the baseline expression level of the gene. Therefore, it's hard for me to give you a quantitative answer. If you and other users would find it useful, we might consider providing a power analysis tool in the future.

> Also, do you have an optimum suggested number/percentage of negative controls? Any experimental design suggestions to optimize the use of SCEPTRE low moi?

I think a few dozen control gRNAs is a good number, but we haven't rigorously explored this question yet. As far as other experimental design suggestions, one that comes to mind is to do sample prep and sequencing on your cells with negative control perturbations in the same batch as all the other cells; do not process your cells with negative control perturbations differently than your other cells. We are considering including a page on experimental design in a future iteration of our website.

**Comment by pipes82** [comment]
Hi, 

Thank you for the prompt response! By signature, I only meant identifying the DE genes for each of the targets, which is what you surmised. 

Regarding the question about the power to detect associations between perturbation and genes, I realize that you can't give a quantitative answer as we would need to perform a power calculation, but I was wondering if you had a minimum number of cells that you thought (off the cuff) would generally not have enough power to detect many gene expression changes. For instance, if I told you that I had 80 cells per perturbation, would you definitely be worried about my power to detect associations? 

If you don't have such a minimum # cells in mind, that's fine too. Your responses have been really helpful, and I appreciate your time to answer my questions and provide suggestions.

Best,
Mary

**Comment by timothy-barry** [comment]
Hi Mary,

> I was wondering if you had a minimum number of cells that you thought (off the cuff) would generally not have enough power to detect many gene expression changes. For instance, if I told you that I had 80 cells per perturbation, would you definitely be worried about my power to detect associations?

As Gene mentioned, power depends both on the number of cells per perturbation and on the expression level of the genes. In general I think 80 cells per targeting perturbation should be fine. Note that sceptre automatically removes perturbation-gene pairs with small effective sample size; see the article on low-MOI QC.

**Comment by pipes82** [comment]
Thanks so much, this is very helpful. I appreciate you taking the time to respond!
