### ISSUE TITLE
Unsure about 'p_value' and 'significant' columns on results_run_discovery_analysis output dataframe

### ISSUE THREAD

**Issue by ale-gomez** [Katsevich-Lab/sceptre#67]
Hello,
I was trying to carry out some analysis on my CRISPRi data and so far it has worked very well, however I needed some clarification about whether we're provided in the resulting dataframe the fdr/BH-adjusted p values, or just nominal p values in the 'p_value' column. I thought these p_values might be adjusted given the analysis parameters, but under the significant column, some of these are considered 'FALSE' under the 'significant' column, while some others are 'TRUE' but I'm not sure what basis the 'significant' column in the dataframe is using to call whether the result is significant or not? If we're not provided the adjusted p values, is there a way to include them in the resulting 'discovery analysis' dataframe? I tried looking through the manual but wasn't sure. Thank you so much for taking the time to clarify this!

**Comment by timothy-barry** [comment]
Hi Ale, good question. The p-values in the `p_value` column are raw (i.e., unadjusted) p-values. Internally, sceptre adjusts the p-values (via BH, for example) and then determines which pairs are significant by thresholding the adjusted p-values. The adjusted p-values, however, are not returned as part of the output.

If you would like to obtain the adjusted p-values, you can do so via `p.adjust(result_df$p_value, method = "BH")`, where `result_df` is the result data frame.

**Comment by ale-gomez** [comment]
Ah I see, it's very clear now, thank you!
