### ISSUE TITLE
Plotting Response Expression for a Given Target vs. Unperturbed/Control Cells

### ISSUE THREAD

**Issue by ale-gomez** [Katsevich-Lab/sceptre#72]
Hello,
  I was trying to obtain some information that's not currently part of the output from SCEPTRE and I was hoping to get your assistance as to how/if I can obtain this information. I have a high MOI, left-sided, union, cis-pair analysis with 1.5 Mb distance threshold (I can also provide more info as needed). For a given gene of interest, I was trying to make a boxplot that shows the levels of expression of that gene in cells with the guides targetting a given candidate enhancer as compared to cells without those gRNAs or the non-targeting control cells. My question is whether it would be possible and how I would go about extracting this kind of information from the output or the sceptre_object. Let me know if this makes sense and if there's any other information I could provide. I've attached a sample image below. Thank you in advance!

Best,
Alejandro.
![Example](https://github.com/Katsevich-Lab/sceptre/assets/134737543/c5f68f35-91c2-437e-83db-5a39d8d0039b)

**Comment by timothy-barry** [comment]
Hi Ale,

This is a great question, and we were thinking about adding a feature along these lines to the software. To make sure I understand, the idea would be to create a plot like this for a _given_ gene-target pair? So you would supply the ID of a gene and the ID of a gRNA target, and then a plot like this would be rendered.

Tim

**Comment by ale-gomez** [comment]
Hi Tim, 
  Yes this would be great and that's what we're aiming to get! To give you some context, in our study, we're interested in functionally validating that a certain genetic variant (or candidate enhancer region) is involved in (or linked) to a given gene we already believe the variant is linked to via other assays or computational models. Because this is the case, it would be nice to show that, for a given gRNA set (say there are 4 individual gRNAs for candidate enhancer 1) targeting that same variant region, there is downregulation (or just dysregulation) of a given gene response.

**Comment by timothy-barry** [comment]
That sounds like an exciting study!

Below, see the function `plot_response_grna_target_pair`, which takes as arguments a `sceptre_object`, `response_id`, and `grna_target` and creates the plot similar to the one you described. (The function creates a violin plot, drawing the median of the distribution as a horizontal line.) Currently, `plot_response_grna_target_pair` works only when `grna_integration_strategy` is set to `"union"` and  `control_group` is set to `"complement_set`" (as should be the case for your data). Note also that this function should be called after `run_qc` is called.

```
library(sceptre)

# 1. load data
directories <- paste0(system.file("extdata", package = "sceptre"),
                      "/highmoi_example/gem_group_", 1:2)
data(grna_target_data_frame_highmoi)
sceptre_object <- import_data_from_cellranger(directories = directories,
                                              moi = "high",
                                              grna_target_data_frame = grna_target_data_frame_highmoi)
print(sceptre_object)

# 2. set the analysis parameters
positive_control_pairs <- construct_positive_control_pairs(sceptre_object)
discovery_pairs <- construct_cis_pairs(sceptre_object,
                                       positive_control_pairs = positive_control_pairs,
                                       distance_threshold = 5e6)
sceptre_object <- set_analysis_parameters(
  sceptre_object = sceptre_object,
  discovery_pairs = discovery_pairs,
  positive_control_pairs = positive_control_pairs,
  side = "left")
print(sceptre_object)

# 3. assign grnas
plot_grna_count_distributions(sceptre_object)
sceptre_object <- sceptre_object |> assign_grnas(parallel = TRUE)
plot(sceptre_object)
print(sceptre_object)

# 4. run qc
plot_covariates(sceptre_object, p_mito_threshold = 0.075)
sceptre_object <- sceptre_object |> run_qc(p_mito_threshold = 0.075)
plot(sceptre_object)
print(sceptre_object)

# 5. run the calibration check
sceptre_object <- run_calibration_check(sceptre_object, parallel = TRUE)
plot(sceptre_object)
print(sceptre_object)

# 6. run the power check
sceptre_object <- run_power_check(sceptre_object, parallel = TRUE)
plot(sceptre_object)
print(sceptre_object)

# 7. run discovery analysis
sceptre_object <- run_discovery_analysis(sceptre_object, parallel = TRUE)
plot(sceptre_object)
print(sceptre_object)


# A function to plot a given response-gRNA-target pair
# NOTE: this function is designed for the union gRNA integration strategy and complement set control group
plot_response_grna_target_pair <- function(sceptre_object, response_id, grna_target) {
  # check that response_id and grna_target are present in the data
  grna_targets <- names(sceptre_object@grna_assignments$grna_group_idxs)
  if (!(grna_target %in% grna_targets)) {
    stop(paste0("gRNA target '", grna_target, "' is not present in the data."))
  }
  response_matrix <- sceptre_object@response_matrix
  response_ids <- rownames(sceptre_object@response_matrix)
  if (!(response_id %in% response_ids)) {
    stop(paste0("Response ID '", response_id, "' is not present in the data."))
  }
  cells_in_use <- sceptre_object@cells_in_use

  # extract the counts and (if applicable) p-value for this pair
  y <- sceptre:::load_csr_row(j = response_matrix@j,
                              p = response_matrix@p,
                              x = response_matrix@x,
                              row_idx = which(response_ids == response_id),
                              n_cells = ncol(response_matrix))[cells_in_use]
  response_n_umis <- sceptre_object@covariate_data_frame[cells_in_use, "response_n_umis"]
  normalized_counts <- log(10000 * y/response_n_umis + 1)
  trt_vect <- rep("Unpert.", length(y))
  trt_vect[sceptre_object@grna_assignments$grna_group_idxs[[grna_target]]] <- "Pert."

  # construct the data frame to plot
  to_plot <- data.frame(normalized_count = normalized_counts,
                        treatment = trt_vect |> factor())

  # create the plot
  p <- ggplot2::ggplot(data = to_plot, mapping = ggplot2::aes(x = treatment, y = normalized_count)) +
    ggplot2::geom_jitter(col = "grey75", size = 0.9, alpha = 0.05) +
    ggplot2::geom_violin(mapping = ggplot2::aes(col = treatment), draw_quantiles = 0.5, fill = NA) +
    sceptre:::get_my_theme() +
    ggplot2::theme(legend.position = "none") +
    ggplot2::scale_color_manual(values = c("dodgerblue3", "black")) +
    ggplot2::xlab("Treatment status") +
    ggplot2::ylab("Relative expression")
  return(p)
}

# plot a couple examples
plot_response_grna_target_pair(sceptre_object, "ENSG00000147454", "candidate_enh_19")
plot_response_grna_target_pair(sceptre_object, "ENSG00000148334", "candidate_enh_22")
```

Hopefully this serves as a decent starting point. We'll add a more fleshed out version of this function to a future update of the package.

**Comment by ale-gomez** [comment]
Thank you so much for putting this together for me! One question I have is does this plot take confounders into account? I'm guessing that might be difficult to do in this case?

**Comment by timothy-barry** [comment]
Hi Ale,

No problem! We'll be adding something like this to the package in the nearish future.

The plot takes the number of gene UMIs sequenced in a given cell (i.e., sequencing depth) into account. It does not take any other covariate into account.

Yes, it would be possible to show the significance between the two violins in the form of a q-value, for example. We'll add this to the to-do list.

**Comment by ale-gomez** [comment]
Hey Tim, 
Thank you for the clarification and your help as always. I look forward to SCEPTRE's updates in the future! It has already proven to be very helpful for my data analysis so far.

**Comment by nhu-github** [comment]
Hi,
Is this feature included in Nextflow pipeline?
