### ISSUE TITLE
Update the sentence “support for Parse Biosciences outputs is coming soon” in the vignette

### ISSUE THREAD

**Issue by ekatsevi** [Katsevich-Lab/sceptre#81]

**Comment by timothy-barry** [comment]
Should we consider linking directly to the first chapter of the book instead? I know that we've discussed this before, but the first chapter of the book now has diverged from the vignette in several respects.

**Comment by ekatsevi** [comment]
This is another instance of the vexing "duplication of information" issue we face. Bioconductor requires us to have at least one vignette, so regardless of whether we put that vignette on our website or simply link to the first book chapter, we will need to have an up-to-date vignette. So I don't know if letting the vignette fall out of date is a viable option. On the other hand, we probably want to avoid manually updating the vignette when the first book chapter changes. I am wondering whether it's possible to write a small script that reads the `qmd` file for the first book chapter and writes a nearly identical `Rmd` file for the vignette. Then, any updates to the first book chapter can be propagated to the vignette with essentially the push of a button. What do you think?
