### ISSUE TITLE
Questions about grna integration options and grna assignment output

### ISSUE THREAD

**Issue by ejagoda14** [Katsevich-Lab/sceptre#85]
A couple questions:
1. I've been playing around with the latest release and I'm curious about the Bonferroni option for the grna integration strategy. When I run this, I noticed the magnitude of my effect sizes went up but the number of cells per perturbation went way down. Based on these results, it seems to me that this option is maybe only using cells for a given perturbation that have one particular guide? Is that the case?

2. Also, is there a way in general to extract from the sceptre object the specific grna x cell calls? I see the information is likely in sceptre_object@grna_assignments$grna_group_idxs but I'm unclear how to convert the set of indexes listed in that object to the corresponding cell barcodes. This is in service of comparing guide assignments across methods. 

3. How are the numbers of n_nonzero_trt and n_nonzero_cntrl defined? I noticed that for a given grna target the numbers of n_non_zero_trt are not identical for each response_id, so there must be more to this definition than purely presence of grnas for the target.

Thanks!

**Comment by timothy-barry** [comment]
Hi Evvie 🙂

1. For a given target-gene pair, the Bonferonni strategy (i) tests each gRNA targeting a given site (separately) against the gene, and then (ii) combines the p-values across gRNAs via a Boneronni correction. For example, if there are three gRNAs targeting a given site, and if these gRNAs produce p-values p_1, p_2, and p_3, then the Bonferonni-corrected p-value would be (1/3) * min (p_1, p_2, p_3).

`n_nonzero_trt` is defined somewhat differently when `grna_integration_strategy` is set to Boneronni. In particular, `n_nonzero_trt` is defined as the number of cells (with nonzero expression of the gene) containing the gRNA that produced the smallest p-value. So, in the above example, if gRNA-2 produced a smaller p-value than gRNA-1 and gRNA-3, then `n_nonzero_trt` would be defined as the number of cells containing both gRNA-2 and nonzero expression of the gene. The situation is similar for `n_nonzero_cntrl`.

So, to answer your question, yes, the Bonferroni strategy is only using cells for a given target that have one particular guide, where that particular guide is the one that produced the smallest p-value. The "overall" p-value for the target-gene pair (or perturbation-gene pair) is adjusted to account for this selection effect.

2. Here is a function that you can use to obtain the gRNA-to-cell assignments.

```
get_grna_assignments <- function(sceptre_object) {
  if (!sceptre_object@functs_called[["assign_grnas"]]) {
    stop("`assign_grnas()` has not yet been called on the `sceptre_object`.")
  }
  return(sceptre_object@initial_grna_assignment_list)
}
```

We'll be adding this function to a future version of the package. The output is a named list, with each entry corresponding to a different gRNA. The entry for a given gRNA is an integer vector indicating the cells to which that gRNA has been assigned. Note that the assignments correspond to the original (i.e., non-QC'ed) gRNA expression matrix.


3. [This part](https://timothy-barry.github.io/sceptre-book/sceptre.html#sec-sceptre_qc) and [this part](https://timothy-barry.github.io/sceptre-book/run-qc.html#pairwise-qc-parameters) of the book have some discussion about `n_nonzero_trt`. Note, as mentioned above, that `n_nonzero_trt` has a slightly different definition depending on whether you are using the "union" or "bonferonni" gRNA integration strategy.


Hopefully this is helpful. Please let me know if you have any other questions.

**Comment by ekatsevi** [comment]
@timothy-barry:  Related to Evvie's question, how do we define the effect size (i.e. log fold-change) in the context of the Bonferroni option?

**Comment by timothy-barry** [comment]
It is defined as the log-fold change obtained from the gRNA with the smallest p-value.

**Comment by ejagoda14** [comment]
Thanks for these answers. Very informative. 

One follow-up related to the n_nonzero_trt - You said this number is essentially cells with the relevant gRNA(s) (either all gRNAs for the target in the case of union, or the gRNA with the smallest p-value in the case of the Bonferroni) and non-zero expression of the gene. Is sceptre unable to handle cases in which the perturbation leads to a umi count of zero, as those cells would be not included in the treatment cell population? Is it possible this leads to an underestimation of the effect size?

**Comment by timothy-barry** [comment]
Hi Evvie,

Yes, by default, sceptre does not analyze pairs for which the perturbation leads to a UMI count of zero. You could try to analyze these pairs by setting `n_nonzero_trt_thresh` to `0` in `run_qc()`. Unfortunately, at some point, there is so little information available for a given pair that doing statistical inference using sceptre (or any method for that matter) becomes impossible. I think this is part of the reason CRISPRa screens nicely complement CRISPRi screens.

I would not expect the exclusion of pairs for which `n_nonzero_trt` is zero to affect effect size estimation. I hope that I understood your question correctly?

**Comment by ekatsevi** [comment]
To add a bit of clarification: It seems Evvie is talking about *cellwise* QC whereas Tim is talking about *pairwise* QC. We do not specifically filter out *cells* where the gene of interest has a UMI count of zero. We filter out perturbation-gene pairs where there do not exist at least `n_nonzero_trt_thresh` perturbed cells with nonzero UMI counts and at least `n_nonzero_ctrl_thresh` control cells with nonzero UMI counts. As Tim says, we consider these *pairs* not to have enough information to form a statistically confident conclusion. For those pairs `sceptre` does choose to analyze, we keep cells with UMI counts of zero.

**Comment by timothy-barry** [comment]
Closing thread.
